package com.sic.tasa.repositories.impl;

import java.util.ArrayList;
import java.util.List;

import org.springframework.orm.hibernate4.HibernateTemplate;
import org.springframework.stereotype.Repository;

import com.sic.tasa.dataobject.FrmAdjFctrQueryBO;
import com.sic.tasa.exceptions.TASADataAccessException;
import com.sic.tasa.repositories.IFrmAdjFctrQueryRepository;
import com.sic.tasa.util.AtmaLogger;

/*************************************************************************
 * 
 * SIC CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * SIC is a trademark of SIC Company.
 *
 * Copyright ? 2017 SIC. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of SIC
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SIC and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SIC.
 *
 *************************************************************************/
// Author : Generated by ATMA ?
// Revision History :


@Repository
public class FrmAdjFctrQueryRepositoryImpl implements IFrmAdjFctrQueryRepository{

    private static AtmaLogger LOGGER = AtmaLogger.create(FrmAdjFctrQueryRepositoryImpl.class.getName());

    private HibernateTemplate template;


    /*
	 * Method cbofundsClick1
	 * @param frmadjfctrqueryBOReq
	 * @return frmadjfctrqueryBOResp
	 * @throws TASADataAccessException
	 */
    public List<FrmAdjFctrQueryBO> cbofundsClick1(FrmAdjFctrQueryBO frmadjfctrqueryBOReq) throws TASADataAccessException {
	    LOGGER.debug("Entering into the method: cbofundsClick1 and argument : "+frmadjfctrqueryBOReq); 
	    List<FrmAdjFctrQueryBO> frmadjfctrqueryBOResp =new ArrayList<FrmAdjFctrQueryBO>();
	    String sql = "select * from unit_value_adjust_factor where rp_mip_seq =  .cboMIPSeq.Text order by as_of_dt desc";
	    try {
//	         List<IDomainObj>  entityList = template.find(sql,new BeanPropertyRowMapper<IDomainObj>(<IDomainObj>.class));
//	         ObjectCopier.copy(entityList, frmadjfctrqueryBOResp); 
	    	FrmAdjFctrQueryBO BO = new FrmAdjFctrQueryBO();
	    	BO.setCbofunds("CboFunds");
	    	BO.setCbofunds("6");
	    	BO.setCbofunds("8");
	    	frmadjfctrqueryBOResp.add(BO); 
	    	
	    	BO.setCbomipseq("CboMIPSeq");
	    	BO.setCbomipseq("5");    	
	    	BO.setCbomipseq("4");
	    	frmadjfctrqueryBOResp.add(BO);    	   	
	    	
	    }catch (Exception ex) {
            LOGGER.error("Error occurred in method: cbofundsClick1()" +"and terminated due to " + ex.getMessage());
            throw new TASADataAccessException(ex);
        }        
        LOGGER.debug("Exiting the method: cbofundsClick1()"+"return : "+frmadjfctrqueryBOResp);
         return frmadjfctrqueryBOResp;
    }
    /*
	 * Method formLoad1
	 * @param frmadjfctrqueryBOReq
	 * @return frmadjfctrqueryBOResp
	 * @throws TASADataAccessException
	 */
    public List<FrmAdjFctrQueryBO> formLoad1(FrmAdjFctrQueryBO frmadjfctrqueryBOReq) throws TASADataAccessException {
	    LOGGER.debug("Entering into the method: formLoad1 and argument : "+frmadjfctrqueryBOReq); 
	    List<FrmAdjFctrQueryBO> frmadjfctrqueryBOResp =new ArrayList<FrmAdjFctrQueryBO>();
	    String sql = "SELECT full_nm, rp_mip_seq, e_invst_instrument_seq FROM rp_modified_investment_pool ORDER BY full_nm";
	    try {
//	         List<IDomainObj>  entityList = template.find(sql,new BeanPropertyRowMapper<IDomainObj>(<IDomainObj>.class));
//	         ObjectCopier.copy(entityList, frmadjfctrqueryBOResp);
	    	FrmAdjFctrQueryBO FrmAdjFctrQueryBO = new FrmAdjFctrQueryBO();
	    	FrmAdjFctrQueryBO.setCbofunds("CboFunds");
	    	FrmAdjFctrQueryBO.setCbofunds("1");
	    	FrmAdjFctrQueryBO.setCbofunds("2");
	    	frmadjfctrqueryBOResp.add(FrmAdjFctrQueryBO); 
	    	
	    	FrmAdjFctrQueryBO.setCbomipseq("CboMIPSeq");
	    	FrmAdjFctrQueryBO.setCbomipseq("5");    	
	    	FrmAdjFctrQueryBO.setCbomipseq("4");
	    	frmadjfctrqueryBOResp.add(FrmAdjFctrQueryBO);
	    }catch (Exception ex) {
            LOGGER.error("Error occurred in method: formLoad1()" +"and terminated due to " + ex.getMessage());
            throw new TASADataAccessException(ex);
        }        
        LOGGER.debug("Exiting the method: formLoad1()"+"return : "+frmadjfctrqueryBOResp);
         return frmadjfctrqueryBOResp;
    }

}