package com.sic.tasa.dataobject;

import java.io.Serializable;  
/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2017 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class FrmDivdMaintBO implements Serializable{


    private String cbomipseq; 

    private String cmdrefresh; 

    private String cmdclose; 

    private String cboinvstinstrmntseq; 

    private String cmdcomputenav; 

    private String txtnavcomputed; 

    private String txtnavaudited; 

    private String txtnavunaudited; 

    private String txtactdollars; 

    private String txtactshares; 

    private String txtactrate; 

    private String txtestrate; 

    private String cboesttypecd; 

    private String cmdselectfund; 

    private String cbofunds; 

    private String cmdsave; 

    private String cmdclear; 

    private String lblexplanation; 

    private String lblmessage; 

    private String lblactapplieddate; 

    private String lblnavaudited; 

    private String lblnavunaudited; 

    private String lblnavcomputed; 

    private String lblnavs; 

    private String lblactdollars; 

    private String lblactshares; 

    private String lblactrate; 

    private String lblactpaiddate; 

    private String lblactual; 

    private String lblestrate; 

    private String lblestexdate; 

    private String lblesttypecd; 

    private String lblestimated; 

    private String lblexdate; 

    private String lblfund; 

    public String getCboMIPSeq() {
        return cbomipseq;
    }

    public void setCboMIPSeq(String cbomipseq ) {
        this.cbomipseq = cbomipseq;
    }
    
    public String getCmdRefresh() {
        return cmdrefresh;
    }

    public void setCmdRefresh(String cmdrefresh ) {
        this.cmdrefresh = cmdrefresh;
    }
    
    public String getCmdClose() {
        return cmdclose;
    }

    public void setCmdClose(String cmdclose ) {
        this.cmdclose = cmdclose;
    }
    
    public String getCboInvstInstrmntSeq() {
        return cboinvstinstrmntseq;
    }

    public void setCboInvstInstrmntSeq(String cboinvstinstrmntseq ) {
        this.cboinvstinstrmntseq = cboinvstinstrmntseq;
    }
    
    public String getCmdComputeNAV() {
        return cmdcomputenav;
    }

    public void setCmdComputeNAV(String cmdcomputenav ) {
        this.cmdcomputenav = cmdcomputenav;
    }
    
    public String getTxtNAVComputed() {
        return txtnavcomputed;
    }

    public void setTxtNAVComputed(String txtnavcomputed ) {
        this.txtnavcomputed = txtnavcomputed;
    }
    
    public String getTxtNAVAudited() {
        return txtnavaudited;
    }

    public void setTxtNAVAudited(String txtnavaudited ) {
        this.txtnavaudited = txtnavaudited;
    }
    
    public String getTxtNAVUnaudited() {
        return txtnavunaudited;
    }

    public void setTxtNAVUnaudited(String txtnavunaudited ) {
        this.txtnavunaudited = txtnavunaudited;
    }
    
    public String getTxtActDollars() {
        return txtactdollars;
    }

    public void setTxtActDollars(String txtactdollars ) {
        this.txtactdollars = txtactdollars;
    }
    
    public String getTxtActShares() {
        return txtactshares;
    }

    public void setTxtActShares(String txtactshares ) {
        this.txtactshares = txtactshares;
    }
    
    public String getTxtActRate() {
        return txtactrate;
    }

    public void setTxtActRate(String txtactrate ) {
        this.txtactrate = txtactrate;
    }
    
    public String getTxtEstRate() {
        return txtestrate;
    }

    public void setTxtEstRate(String txtestrate ) {
        this.txtestrate = txtestrate;
    }
    
    public String getCboEstTypeCd() {
        return cboesttypecd;
    }

    public void setCboEstTypeCd(String cboesttypecd ) {
        this.cboesttypecd = cboesttypecd;
    }
    
    public String getCmdSelectFund() {
        return cmdselectfund;
    }

    public void setCmdSelectFund(String cmdselectfund ) {
        this.cmdselectfund = cmdselectfund;
    }
    
    public String getCboFunds() {
        return cbofunds;
    }

    public void setCboFunds(String cbofunds ) {
        this.cbofunds = cbofunds;
    }
    
    public String getCmdSave() {
        return cmdsave;
    }

    public void setCmdSave(String cmdsave ) {
        this.cmdsave = cmdsave;
    }
    
    public String getCmdClear() {
        return cmdclear;
    }

    public void setCmdClear(String cmdclear ) {
        this.cmdclear = cmdclear;
    }
    
    public String getLblExplanation() {
        return lblexplanation;
    }

    public void setLblExplanation(String lblexplanation ) {
        this.lblexplanation = lblexplanation;
    }
    
    public String getLblMessage() {
        return lblmessage;
    }

    public void setLblMessage(String lblmessage ) {
        this.lblmessage = lblmessage;
    }
    
    public String getLblActAppliedDate() {
        return lblactapplieddate;
    }

    public void setLblActAppliedDate(String lblactapplieddate ) {
        this.lblactapplieddate = lblactapplieddate;
    }
    
    public String getLblNAVAudited() {
        return lblnavaudited;
    }

    public void setLblNAVAudited(String lblnavaudited ) {
        this.lblnavaudited = lblnavaudited;
    }
    
    public String getLblNAVUnaudited() {
        return lblnavunaudited;
    }

    public void setLblNAVUnaudited(String lblnavunaudited ) {
        this.lblnavunaudited = lblnavunaudited;
    }
    
    public String getLblNAVComputed() {
        return lblnavcomputed;
    }

    public void setLblNAVComputed(String lblnavcomputed ) {
        this.lblnavcomputed = lblnavcomputed;
    }
    
    public String getLblNAVs() {
        return lblnavs;
    }

    public void setLblNAVs(String lblnavs ) {
        this.lblnavs = lblnavs;
    }
    
    public String getLblActDollars() {
        return lblactdollars;
    }

    public void setLblActDollars(String lblactdollars ) {
        this.lblactdollars = lblactdollars;
    }
    
    public String getLblActShares() {
        return lblactshares;
    }

    public void setLblActShares(String lblactshares ) {
        this.lblactshares = lblactshares;
    }
    
    public String getLblActRate() {
        return lblactrate;
    }

    public void setLblActRate(String lblactrate ) {
        this.lblactrate = lblactrate;
    }
    
    public String getLblActPaidDate() {
        return lblactpaiddate;
    }

    public void setLblActPaidDate(String lblactpaiddate ) {
        this.lblactpaiddate = lblactpaiddate;
    }
    
    public String getLblActual() {
        return lblactual;
    }

    public void setLblActual(String lblactual ) {
        this.lblactual = lblactual;
    }
    
    public String getLblEstRate() {
        return lblestrate;
    }

    public void setLblEstRate(String lblestrate ) {
        this.lblestrate = lblestrate;
    }
    
    public String getLblEstExDate() {
        return lblestexdate;
    }

    public void setLblEstExDate(String lblestexdate ) {
        this.lblestexdate = lblestexdate;
    }
    
    public String getLblEstTypeCd() {
        return lblesttypecd;
    }

    public void setLblEstTypeCd(String lblesttypecd ) {
        this.lblesttypecd = lblesttypecd;
    }
    
    public String getLblEstimated() {
        return lblestimated;
    }

    public void setLblEstimated(String lblestimated ) {
        this.lblestimated = lblestimated;
    }
    
    public String getLblExDate() {
        return lblexdate;
    }

    public void setLblExDate(String lblexdate ) {
        this.lblexdate = lblexdate;
    }
    
    public String getLblFund() {
        return lblfund;
    }

    public void setLblFund(String lblfund ) {
        this.lblfund = lblfund;
    }
    
    @Override
    public String toString() {
      return "FrmDivdMaintBO [cbomipseq = + cbomipseq +  ,cmdrefresh = + cmdrefresh +  ,cmdclose = + cmdclose +  ,cboinvstinstrmntseq = + cboinvstinstrmntseq +  ,cmdcomputenav = + cmdcomputenav +  ,txtnavcomputed = + txtnavcomputed +  ,txtnavaudited = + txtnavaudited +  ,txtnavunaudited = + txtnavunaudited +  ,txtactdollars = + txtactdollars + ,txtactshares = + txtactshares +  ,txtactrate = + txtactrate +  ,txtestrate = + txtestrate +  ,cboesttypecd = + cboesttypecd +  ,cmdselectfund = + cmdselectfund +  ,cbofunds = + cbofunds +  ,cmdsave = + cmdsave +  ,cmdclear = + cmdclear +  ,lblexplanation = + lblexplanation +  ,lblmessage = + lblmessage +  ,lblactapplieddate = + lblactapplieddate +  ,lblnavaudited = + lblnavaudited +  ,lblnavunaudited = + lblnavunaudited +  ,lblnavcomputed = + lblnavcomputed +  ,lblnavs = + lblnavs +  ,lblactdollars = + lblactdollars +  ,lblactshares = + lblactshares +  ,lblactrate = + lblactrate +  ,lblactpaiddate = + lblactpaiddate +  ,lblactual = + lblactual +  ,lblestrate = + lblestrate +  ,lblestexdate = + lblestexdate +  ,lblesttypecd = + lblesttypecd +  ,lblestimated = + lblestimated +  ,lblexdate = + lblexdate +  ,lblfund = + lblfund]";
    }
    
}