package com.sic.tasa.dataobject;

import java.io.Serializable;
/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2017 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class FrmDailyNavMaintenanceBO implements Serializable{


    /**
	 * 
	 */
	private static final long serialVersionUID = 4930594445862092055L;

	private String txtasofdate; 

    private String txtmanualval; 

    private String cmddelete; 

    private String cmdclose; 

    private String cmdaddmodify; 

    private String txtmanualrepeat; 

    private String cmdselfund; 

	private String cbofunds; 

    private String label2; 

    private String lblestimatedval; 

    private String lblmanval; 

    private String lblmanrepeat; 

    private String label5; 

    private String lblunaudited; 

    private String label4; 

    private String label3; 

    private String label1; 
    
    private String manval;
    
    private String fundSeq;
    
    private String rp_contract_id;
    
    private String Legal_Plan_nm;
    
    private String RP_CPSRPD_FUND_SEQ;
    
    private String UNIT_VALUE;
    
    public String getRp_contract_id() {
		return rp_contract_id;
	}


	public void setRp_contract_id(String rp_contract_id) {
		this.rp_contract_id = rp_contract_id;
	}


	public String getLegal_Plan_nm() {
		return Legal_Plan_nm;
	}


	public void setLegal_Plan_nm(String legal_Plan_nm) {
		Legal_Plan_nm = legal_Plan_nm;
	}


	public String getRP_CPSRPD_FUND_SEQ() {
		return RP_CPSRPD_FUND_SEQ;
	}


	public void setRP_CPSRPD_FUND_SEQ(String rP_CPSRPD_FUND_SEQ) {
		RP_CPSRPD_FUND_SEQ = rP_CPSRPD_FUND_SEQ;
	}


	public String getUNIT_VALUE() {
		return UNIT_VALUE;
	}


	public void setUNIT_VALUE(String uNIT_VALUE) {
		UNIT_VALUE = uNIT_VALUE;
	}


	public String getTxtasofdate() {
		return txtasofdate;
	}


	public void setTxtasofdate(String txtasofdate) {
		this.txtasofdate = txtasofdate;
	}


	public String getTxtmanualval() {
		return txtmanualval;
	}


	public void setTxtmanualval(String txtmanualval) {
		this.txtmanualval = txtmanualval;
	}


	public String getCmddelete() {
		return cmddelete;
	}


	public void setCmddelete(String cmddelete) {
		this.cmddelete = cmddelete;
	}


	public String getCmdclose() {
		return cmdclose;
	}


	public void setCmdclose(String cmdclose) {
		this.cmdclose = cmdclose;
	}


	public String getCmdaddmodify() {
		return cmdaddmodify;
	}


	public void setCmdaddmodify(String cmdaddmodify) {
		this.cmdaddmodify = cmdaddmodify;
	}


	public String getTxtmanualrepeat() {
		return txtmanualrepeat;
	}


	public void setTxtmanualrepeat(String txtmanualrepeat) {
		this.txtmanualrepeat = txtmanualrepeat;
	}



	public String getCbofunds() {
		return cbofunds;
	}


	public void setCbofunds(String cbofunds) {
		this.cbofunds = cbofunds;
	}


	public String getLabel2() {
		return label2;
	}


	public void setLabel2(String label2) {
		this.label2 = label2;
	}


	public String getLblestimatedval() {
		return lblestimatedval;
	}


	public void setLblestimatedval(String lblestimatedval) {
		this.lblestimatedval = lblestimatedval;
	}


	public String getLblmanval() {
		return lblmanval;
	}


	public void setLblmanval(String lblmanval) {
		this.lblmanval = lblmanval;
	}


	public String getLblmanrepeat() {
		return lblmanrepeat;
	}


	public void setLblmanrepeat(String lblmanrepeat) {
		this.lblmanrepeat = lblmanrepeat;
	}


	public String getLabel5() {
		return label5;
	}


	public void setLabel5(String label5) {
		this.label5 = label5;
	}


	public String getLblunaudited() {
		return lblunaudited;
	}


	public void setLblunaudited(String lblunaudited) {
		this.lblunaudited = lblunaudited;
	}


	public String getLabel4() {
		return label4;
	}


	public void setLabel4(String label4) {
		this.label4 = label4;
	}


	public String getLabel3() {
		return label3;
	}


	public void setLabel3(String label3) {
		this.label3 = label3;
	}


	public String getLabel1() {
		return label1;
	}


	public void setLabel1(String label1) {
		this.label1 = label1;
	}


	public String getManval() {
		return manval;
	}


	public void setManval(String manval) {
		this.manval = manval;
	}


	public String getFundSeq() {
		return fundSeq;
	}

	public void setFundSeq(String fundSeq) {
		this.fundSeq = fundSeq;
	}
	
	public String getCmdselfund() {
		return cmdselfund;
	}


	public void setCmdselfund(String cmdselfund) {
		this.cmdselfund = cmdselfund;
	}


	@Override
    public String toString() {
      return "FrmDailyNavMaintenanceBO [txtasofdate =" + txtasofdate + " ,txtmanualval =" + txtmanualval + " ,cmddelete =" + cmddelete + " ,cmdclose =" + cmdclose + " ,cmdaddmodify =" + cmdaddmodify + " ,txtmanualrepeat =" + txtmanualrepeat + " ,cmdselfund =" + cmdselfund + " ,cbofunds =" + cbofunds + " ,label2 =" + label2 + " ,lblestimatedval =" + lblestimatedval + " ,lblmanval =" + lblmanval + " ,lblmanrepeat =" + lblmanrepeat + " ,label5 =" + label5 + " ,lblunaudited =" + lblunaudited + " ,label4 =" + label4 + " ,label3 =" + label3 + " ,label1 =" + label1+"]";
    }
    
}