package com.sic.tasa.rest;


import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import com.sic.tasa.dataobject.FrmDailyNavMaintenanceBO;
import com.sic.tasa.exceptions.TASARESTException;
import com.sic.tasa.service.IFrmDailyNavMaintenanceService;
import com.sic.tasa.util.AtmaLogger;


/*************************************************************************
 * 
 * SIC CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * SIC is a trademark of SIC Company.
 *
 * Copyright ? 2017 SIC. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of SIC
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SIC and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SIC.
 *
 *************************************************************************/
// Author : Generated by ATMA ?
// Revision History :


@RestController
@RequestMapping(value = "/FrmDailyNavMaintenanceController")
public class FrmDailyNavMaintenanceController {

    private static AtmaLogger LOGGER = AtmaLogger.create(FrmDailyNavMaintenanceController.class);

		@Autowired
		private IFrmDailyNavMaintenanceService frmdailynavmaintenanceService;

		public void setFrmDailyNavMaintenanceService(IFrmDailyNavMaintenanceService frmdailynavmaintenanceService) {
		    this.frmdailynavmaintenanceService = frmdailynavmaintenanceService;
		}

    /*
     * Method populatesfgfund
     * @param frmdailynavmaintenanceBOReq
     * @return frmdailynavmaintenanceBOResp
     * @throws TASARESTException
    */
    @RequestMapping(value = "/populatesfgfund" , method = RequestMethod.POST)
    public List<FrmDailyNavMaintenanceBO> populatesfgfund() throws TASARESTException{ 
    	LOGGER.debug("Entering into the method: populatesfgfund "); 
        List<FrmDailyNavMaintenanceBO> frmdailynavmaintenanceBOResp =  new ArrayList<FrmDailyNavMaintenanceBO>();
        try{
            frmdailynavmaintenanceBOResp = frmdailynavmaintenanceService.populatesfgfund();
        }
        catch (Exception ex){
            LOGGER.error("Error occurred in method: populatesfgfund and terminated due to " + ex.getMessage());
            throw new TASARESTException(ex);
        }
        LOGGER.debug("Exiting the method: populatesfgfund()and return : "+frmdailynavmaintenanceBOResp);
        return frmdailynavmaintenanceBOResp;
    }
//    /*
//     * Method cmdaddmodifyclick
//     * @param frmdailynavmaintenanceBOReq
//     * @return frmdailynavmaintenanceBOResp
//     * @throws TASARESTException
//    */
//    @RequestMapping(value = "/cmdaddmodifyclick" , method = RequestMethod.POST)
//    public List<FrmDailyNavMaintenanceBO> cmdaddmodifyclick(@RequestBody FrmDailyNavMaintenanceBO frmdailynavmaintenanceBOReq) throws TASARESTException{    
//        LOGGER.debug("Entering into the method: cmdaddmodifyclick and argument : "+frmdailynavmaintenanceBOReq); 
//        List<FrmDailyNavMaintenanceBO> frmdailynavmaintenanceBOResp =  new ArrayList<FrmDailyNavMaintenanceBO>();
//        try{
//            frmdailynavmaintenanceBOResp = frmdailynavmaintenanceService.cmdaddmodifyclick(frmdailynavmaintenanceBOReq);
//        }
//        catch (Exception ex){
//            LOGGER.error("Error occurred in method: cmdaddmodifyclick and terminated due to " + ex.getMessage());
//            throw new TASARESTException(ex);
//        }
//        LOGGER.debug("Exiting the method: cmdaddmodifyclick()and return : "+frmdailynavmaintenanceBOResp);
//        return frmdailynavmaintenanceBOResp;
//    }
    /*
     * Method cmdaddmodifyclick1
     * @param frmdailynavmaintenanceBOReq
     * @return frmdailynavmaintenanceBOResp
     * @throws TASARESTException
    */
    @RequestMapping(value = "/cmdaddmodifyclick1" , method = RequestMethod.POST)
    public List<FrmDailyNavMaintenanceBO> cmdaddmodifyclick1(@RequestBody FrmDailyNavMaintenanceBO frmdailynavmaintenanceBOReq) throws TASARESTException{    
        LOGGER.debug("Entering into the method: cmdaddmodifyclick1 and argument : "+frmdailynavmaintenanceBOReq); 
        List<FrmDailyNavMaintenanceBO> frmdailynavmaintenanceBOResp =  new ArrayList<FrmDailyNavMaintenanceBO>();
        try{
            frmdailynavmaintenanceBOResp = frmdailynavmaintenanceService.cmdaddmodifyclick1(frmdailynavmaintenanceBOReq);
        }
        catch (Exception ex){
            LOGGER.error("Error occurred in method: cmdaddmodifyclick1 and terminated due to " + ex.getMessage());
            throw new TASARESTException(ex);
        }
        LOGGER.debug("Exiting the method: cmdaddmodifyclick1()and return : "+frmdailynavmaintenanceBOResp);
        return frmdailynavmaintenanceBOResp;
    }
    
    /*
     * Method cmdaddmodifyclick2
     * @param frmdailynavmaintenanceBOReq
     * @return frmdailynavmaintenanceBOResp
     * @throws TASARESTException
    */
    @RequestMapping(value = "/cmdaddmodifyclick2" , method = RequestMethod.POST)
    public List<FrmDailyNavMaintenanceBO> cmdaddmodifyclick2(@RequestBody FrmDailyNavMaintenanceBO frmdailynavmaintenanceBOReq) throws TASARESTException{    
        LOGGER.debug("Entering into the method: cmdaddmodifyclick2 and argument : "+frmdailynavmaintenanceBOReq); 
        List<FrmDailyNavMaintenanceBO> frmdailynavmaintenanceBOResp =  new ArrayList<FrmDailyNavMaintenanceBO>();
        try{
            frmdailynavmaintenanceBOResp = frmdailynavmaintenanceService.cmdaddmodifyclick2(frmdailynavmaintenanceBOReq);
        }
        catch (Exception ex){
            LOGGER.error("Error occurred in method: cmdaddmodifyclick2 and terminated due to " + ex.getMessage());
            throw new TASARESTException(ex);
        }
        LOGGER.debug("Exiting the method: cmdaddmodifyclick2()and return : "+frmdailynavmaintenanceBOResp);
        return frmdailynavmaintenanceBOResp;
    }
    /*
     * Method cmdaddmodifyclick2
     * @param frmdailynavmaintenanceBOReq
     * @return frmdailynavmaintenanceBOResp
     * @throws TASARESTException
    */
    @RequestMapping(value = "/cmdaddmodifyclick3" , method = RequestMethod.POST)
    public List<FrmDailyNavMaintenanceBO> cmdaddmodifyclick3(@RequestBody FrmDailyNavMaintenanceBO frmdailynavmaintenanceBOReq) throws TASARESTException{    
        LOGGER.debug("Entering into the method: cmdaddmodifyclick3 and argument : "+frmdailynavmaintenanceBOReq); 
        List<FrmDailyNavMaintenanceBO> frmdailynavmaintenanceBOResp =  new ArrayList<FrmDailyNavMaintenanceBO>();
        try{
            frmdailynavmaintenanceBOResp = frmdailynavmaintenanceService.cmdaddmodifyclick3(frmdailynavmaintenanceBOReq);
        }
        catch (Exception ex){
            LOGGER.error("Error occurred in method: cmdaddmodifyclick3 and terminated due to " + ex.getMessage());
            throw new TASARESTException(ex);
        }
        LOGGER.debug("Exiting the method: cmdaddmodifyclick3()and return : "+frmdailynavmaintenanceBOResp);
        return frmdailynavmaintenanceBOResp;
    }
    /*
     * Method cmddeleteclick
     * @param frmdailynavmaintenanceBOReq
     * @return frmdailynavmaintenanceBOResp
     * @throws TASARESTException
    */
    @RequestMapping(value = "/cmddeleteclick" , method = RequestMethod.POST)
    public List<FrmDailyNavMaintenanceBO> cmddeleteclick(@RequestBody FrmDailyNavMaintenanceBO frmdailynavmaintenanceBOReq) throws TASARESTException{    
        LOGGER.debug("Entering into the method: cmddeleteclick and argument : "+frmdailynavmaintenanceBOReq); 
        List<FrmDailyNavMaintenanceBO> frmdailynavmaintenanceBOResp =  new ArrayList<FrmDailyNavMaintenanceBO>();
        try{
            frmdailynavmaintenanceBOResp = frmdailynavmaintenanceService.cmddeleteclick(frmdailynavmaintenanceBOReq);
        }
        catch (Exception ex){
            LOGGER.error("Error occurred in method: cmddeleteclick and terminated due to " + ex.getMessage());
            throw new TASARESTException(ex);
        }
        LOGGER.debug("Exiting the method: cmddeleteclick()and return : "+frmdailynavmaintenanceBOResp);
        return frmdailynavmaintenanceBOResp;
    }
    /*
     * Method populateselectedfunddetails1
     * @param frmdailynavmaintenanceBOReq
     * @return frmdailynavmaintenanceBOResp
     * @throws TASARESTException
    */
    @RequestMapping(value = "/populateselectedfunddetails1" , method = RequestMethod.POST)
    public List<FrmDailyNavMaintenanceBO> populateselectedfunddetails1(@RequestBody FrmDailyNavMaintenanceBO frmdailynavmaintenanceBOReq) throws TASARESTException{    
        LOGGER.debug("Entering into the method: populateselectedfunddetails1 and argument : "+frmdailynavmaintenanceBOReq); 
        List<FrmDailyNavMaintenanceBO> frmdailynavmaintenanceBOResp =  new ArrayList<FrmDailyNavMaintenanceBO>();
        try{
            frmdailynavmaintenanceBOResp = frmdailynavmaintenanceService.populateselectedfunddetails1(frmdailynavmaintenanceBOReq);
        }
        catch (Exception ex){
            LOGGER.error("Error occurred in method: populateselectedfunddetail1s and terminated due to " + ex.getMessage());
            throw new TASARESTException(ex);
        }
        LOGGER.debug("Exiting the method: populateselectedfunddetail1s()and return : "+frmdailynavmaintenanceBOResp);
        return frmdailynavmaintenanceBOResp;
    }
    /*
     * Method populateselectedfunddetails2
     * @param frmdailynavmaintenanceBOReq
     * @return frmdailynavmaintenanceBOResp
     * @throws TASARESTException
    */
    @RequestMapping(value = "/populateselectedfunddetails2" , method = RequestMethod.POST)
    public List<FrmDailyNavMaintenanceBO> populateselectedfunddetails2(@RequestBody FrmDailyNavMaintenanceBO frmdailynavmaintenanceBOReq) throws TASARESTException{    
        LOGGER.debug("Entering into the method: populateselectedfunddetails2 and argument : "+frmdailynavmaintenanceBOReq); 
        List<FrmDailyNavMaintenanceBO> frmdailynavmaintenanceBOResp =  new ArrayList<FrmDailyNavMaintenanceBO>();
        try{
            frmdailynavmaintenanceBOResp = frmdailynavmaintenanceService.populateselectedfunddetails2(frmdailynavmaintenanceBOReq);
        }
        catch (Exception ex){
            LOGGER.error("Error occurred in method: populateselectedfunddetails2 and terminated due to " + ex.getMessage());
            throw new TASARESTException(ex);
        }
        LOGGER.debug("Exiting the method: populateselectedfunddetails2()and return : "+frmdailynavmaintenanceBOResp);
        return frmdailynavmaintenanceBOResp;
    }
}