package com.sic.tasa.repositories.impl;

import java.util.ArrayList;
import java.util.List;

import org.springframework.orm.hibernate4.HibernateTemplate;
import org.springframework.stereotype.Repository;

import com.sic.tasa.dataobject.FrmGLAccountBO;
import com.sic.tasa.exceptions.TASADataAccessException;
import com.sic.tasa.repositories.IFrmGLAccountRepository;
import com.sic.tasa.util.AtmaLogger;

/*************************************************************************
 * 
 * SIC CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * SIC is a trademark of SIC Company.
 *
 * Copyright ? 2017 SIC. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of SIC
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SIC and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SIC.
 *
 *************************************************************************/
// Author : Generated by ATMA ?
// Revision History :


@Repository
public class FrmGLAccountRepositoryImpl implements IFrmGLAccountRepository{
	
	private static final AtmaLogger LOGGER = AtmaLogger.create(FrmGLAccountRepositoryImpl.class.getName());

    private HibernateTemplate template;
    public boolean insert = false;
    /*
	 * Method cmdqueryClick1
	 * @param frmglaccountBOReq
	 * @return frmglaccountBOResp
	 * @throws TASADataAccessException
	 */
    public List<FrmGLAccountBO> cmdqueryClick1(FrmGLAccountBO frmglaccountBOReq) throws TASADataAccessException {
	    LOGGER.debug("Entering into the method: cmdqueryClick1 and argument : "+frmglaccountBOReq); 
	    List<FrmGLAccountBO> frmglaccountBOResp =new ArrayList<FrmGLAccountBO>();
	    String sql = "SELECT GL_ACCNT_CO_ID GENERAL,GL_ACCNT_NBR_ID LEDGER,GL_ACCNT_CNTR_ID ACCOUNT,";
	    try {
	         /*List<IDomainObj>  entityList = template.find(sql,new BeanPropertyRowMapper<IDomainObj>(<IDomainObj>.class));
	         ObjectCopier.copy(entityList, frmglaccountBOResp); */ 
	    	FrmGLAccountBO bo = new FrmGLAccountBO();
	    	 bo.setGeneral("Data1");
	    	 bo.setLedger("Data2");
	    	 bo.setAccount("Data3");
	    	 bo.setGlAccountProductId("TASA");
	    	 bo.setGlAccountProjectId("SIC");
	    	 bo.setClearingControl("NA");
	    	 bo.setLastUpdatedBy("User");
	    	 bo.setLastUpdated("11/07/2017");
	    	 bo.setSequenceNo("1");
	    	 frmglaccountBOResp.add(bo);
	    }catch (Exception ex) {
            LOGGER.error("Error occurred in method: cmdqueryClick1()" +"and terminated due to " + ex.getMessage());
            throw new TASADataAccessException(ex);
        }        
        LOGGER.debug("Exiting the method: cmdqueryClick1()"+"return : "+frmglaccountBOResp);
         return frmglaccountBOResp;
    }
    
    /*
	 * Method cmdqueryClick1
	 * @param frmglaccountBOReq
	 * @return frmglaccountBOResp
	 * @throws TASADataAccessException
	 */
    public List<FrmGLAccountBO> cmdinsertClick1(List<FrmGLAccountBO> frmglaccountBOReq) throws TASADataAccessException {
	    LOGGER.debug("Entering into the method: cmdinsertClick1 and argument : "+frmglaccountBOReq); 
	    List<FrmGLAccountBO> frmglaccountBOResp =new ArrayList<FrmGLAccountBO>();
	    try {
		    	frmglaccountBOResp = new ArrayList<FrmGLAccountBO>();
		    	FrmGLAccountBO bo1 = new FrmGLAccountBO();
		    	insert = true;
		    	if(insert == true && bo1.getTxtB() != "" && bo1.getTxtC() != "") {
		    		System.out.println("Calling insert query .....");
		    	}
		    	
		    	System.out.println("Calling select query based on sequence no .....");
		    	
		    	for(int i=0;i<frmglaccountBOReq.size();i++) {
				    	 bo1.setGeneral("Gen");
				    	 bo1.setLedger("Led");
				    	 bo1.setAccount("Chennai");
				    	 bo1.setGlAccountProductId("TASA");
				    	 bo1.setGlAccountProjectId("SIC");
				    	 bo1.setClearingControl("NA");
				    	 bo1.setLastUpdatedBy("User");
				    	 bo1.setLastUpdated("10/07/2017");
				    	 bo1.setSequenceNo("1");
			    	 frmglaccountBOResp.add(bo1);
					//frmglaccountBOResp.add(frmglaccountBOReq.get(i));
				}
		    	
	    }catch (Exception ex) {
            LOGGER.error("Error occurred in method: cmdqueryClick1()" +"and terminated due to " + ex.getMessage());
            throw new TASADataAccessException(ex);
        }        
        LOGGER.debug("Exiting the method: cmdqueryClick1()"+"return : "+frmglaccountBOResp);
         return frmglaccountBOResp;
    }
    
    /*
	 * Method formLoad1
	 * @param frmglaccountBOReq
	 * @return frmglaccountBOResp
	 * @throws TASADataAccessException
	 */
    public List<FrmGLAccountBO> formLoad1() throws TASADataAccessException {
	    LOGGER.debug("Entering into the method: formLoad1 and argument : "); 
	    List<FrmGLAccountBO> frmglaccountBOResp =new ArrayList<FrmGLAccountBO>();
	    String sql = "SELECT GL_ACCNT_CO_ID GENERAL,GL_ACCNT_NBR_ID LEDGER,GL_ACCNT_CNTR_ID ACCOUNT,";
	    try {
	         /*List<IDomainObj>  entityList = template.find(sql,new BeanPropertyRowMapper<IDomainObj>(<IDomainObj>.class));
	         ObjectCopier.copy(entityList, frmglaccountBOResp);*/ 
	    	 FrmGLAccountBO bo = new FrmGLAccountBO();
	    	 bo.setGeneral("General");
	    	 bo.setLedger("Ledger");
	    	 bo.setAccount("Chennai");
	    	 bo.setGlAccountProductId("TASA");
	    	 bo.setGlAccountProjectId("SIC");
	    	 bo.setClearingControl("NA");
	    	 bo.setLastUpdatedBy("User");
	    	 bo.setLastUpdated("10/07/2017");
	    	 bo.setSequenceNo("1");
	    	 FrmGLAccountBO bo1 = new FrmGLAccountBO();
	    	 bo1.setGeneral("Gen");
	    	 bo1.setLedger("Led");
	    	 bo1.setAccount("Chennai");
	    	 bo1.setGlAccountProductId("TASA");
	    	 bo1.setGlAccountProjectId("SIC");
	    	 bo1.setClearingControl("NA");
	    	 bo1.setLastUpdatedBy("User");
	    	 bo1.setLastUpdated("10/07/2017");
	    	 bo1.setSequenceNo("1");
	    	 frmglaccountBOResp.add(bo);
	    	 frmglaccountBOResp.add(bo1);
	    }catch (Exception ex) {
            LOGGER.error("Error occurred in method: formLoad1()" +"and terminated due to " + ex.getMessage());
            throw new TASADataAccessException(ex);
        }        
        LOGGER.debug("Exiting the method: formLoad1()"+"return : "+frmglaccountBOResp);
         return frmglaccountBOResp;
    }

}