package com.sic.tasa.dataobject;

import java.io.Serializable;  
/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2017 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class FrmNonSFGheldFundsBO implements Serializable{


    private String txttickersymbol; 

    private String cmdselfund; 

    private String txtseq; 

    private String cboselassetclass; 

    private String cmdsave; 

    private String cbofunds; 

    private String cmdclose; 

    private String cmddelete; 

    private String cmdclear; 

    private String cboassetclass; 

    private String txtname; 

    private String txtcusip; 

    private String lbltickersymbol; 

    private String label4; 

    private String lblassetclass; 

    private String lblname; 

    private String lblcusip;

	public String getTxttickersymbol() {
		return txttickersymbol;
	}

	public void setTxttickersymbol(String txttickersymbol) {
		this.txttickersymbol = txttickersymbol;
	}

	public String getCmdselfund() {
		return cmdselfund;
	}

	public void setCmdselfund(String cmdselfund) {
		this.cmdselfund = cmdselfund;
	}

	public String getTxtseq() {
		return txtseq;
	}

	public void setTxtseq(String txtseq) {
		this.txtseq = txtseq;
	}

	public String getCboselassetclass() {
		return cboselassetclass;
	}

	public void setCboselassetclass(String cboselassetclass) {
		this.cboselassetclass = cboselassetclass;
	}

	public String getCmdsave() {
		return cmdsave;
	}

	public void setCmdsave(String cmdsave) {
		this.cmdsave = cmdsave;
	}

	public String getCbofunds() {
		return cbofunds;
	}

	public void setCbofunds(String cbofunds) {
		this.cbofunds = cbofunds;
	}

	public String getCmdclose() {
		return cmdclose;
	}

	public void setCmdclose(String cmdclose) {
		this.cmdclose = cmdclose;
	}

	public String getCmddelete() {
		return cmddelete;
	}

	public void setCmddelete(String cmddelete) {
		this.cmddelete = cmddelete;
	}

	public String getCmdclear() {
		return cmdclear;
	}

	public void setCmdclear(String cmdclear) {
		this.cmdclear = cmdclear;
	}

	public String getCboassetclass() {
		return cboassetclass;
	}

	public void setCboassetclass(String cboassetclass) {
		this.cboassetclass = cboassetclass;
	}

	public String getTxtname() {
		return txtname;
	}

	public void setTxtname(String txtname) {
		this.txtname = txtname;
	}

	public String getTxtcusip() {
		return txtcusip;
	}

	public void setTxtcusip(String txtcusip) {
		this.txtcusip = txtcusip;
	}

	public String getLbltickersymbol() {
		return lbltickersymbol;
	}

	public void setLbltickersymbol(String lbltickersymbol) {
		this.lbltickersymbol = lbltickersymbol;
	}

	public String getLabel4() {
		return label4;
	}

	public void setLabel4(String label4) {
		this.label4 = label4;
	}

	public String getLblassetclass() {
		return lblassetclass;
	}

	public void setLblassetclass(String lblassetclass) {
		this.lblassetclass = lblassetclass;
	}

	public String getLblname() {
		return lblname;
	}

	public void setLblname(String lblname) {
		this.lblname = lblname;
	}

	public String getLblcusip() {
		return lblcusip;
	}

	public void setLblcusip(String lblcusip) {
		this.lblcusip = lblcusip;
	} 

    
    
}