package com.sic.tasa.dataobject;

import java.io.Serializable;  
/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2017 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class FrmNAVMaintBO implements Serializable{


    private String cmddelete; 

    private String txtreenteramendedaudval; 

    private String cmdadd; 

    private String cmdclose; 

    private String txtamendauditedval; 

    private String txtvalusedbycuv; 

    private String cbofunds; 

    private String cmdselectfund; 

    private String lblmessage; 

    private String label1; 

    private String lblsource; 

    private String lblreenter; 

    private String lblnavdata; 

    private String lblunauditedrate; 

    private String lblamendaudval; 

    private String lblnotifieddate; 

    private String lblfund; 

    private String lblasofdate;

	public String getCmddelete() {
		return cmddelete;
	}

	public void setCmddelete(String cmddelete) {
		this.cmddelete = cmddelete;
	}

	public String getTxtreenteramendedaudval() {
		return txtreenteramendedaudval;
	}

	public void setTxtreenteramendedaudval(String txtreenteramendedaudval) {
		this.txtreenteramendedaudval = txtreenteramendedaudval;
	}

	public String getCmdadd() {
		return cmdadd;
	}

	public void setCmdadd(String cmdadd) {
		this.cmdadd = cmdadd;
	}

	public String getCmdclose() {
		return cmdclose;
	}

	public void setCmdclose(String cmdclose) {
		this.cmdclose = cmdclose;
	}

	public String getTxtamendauditedval() {
		return txtamendauditedval;
	}

	public void setTxtamendauditedval(String txtamendauditedval) {
		this.txtamendauditedval = txtamendauditedval;
	}

	public String getTxtvalusedbycuv() {
		return txtvalusedbycuv;
	}

	public void setTxtvalusedbycuv(String txtvalusedbycuv) {
		this.txtvalusedbycuv = txtvalusedbycuv;
	}

	public String getCbofunds() {
		return cbofunds;
	}

	public void setCbofunds(String cbofunds) {
		this.cbofunds = cbofunds;
	}

	public String getCmdselectfund() {
		return cmdselectfund;
	}

	public void setCmdselectfund(String cmdselectfund) {
		this.cmdselectfund = cmdselectfund;
	}

	public String getLblmessage() {
		return lblmessage;
	}

	public void setLblmessage(String lblmessage) {
		this.lblmessage = lblmessage;
	}

	public String getLabel1() {
		return label1;
	}

	public void setLabel1(String label1) {
		this.label1 = label1;
	}

	public String getLblsource() {
		return lblsource;
	}

	public void setLblsource(String lblsource) {
		this.lblsource = lblsource;
	}

	public String getLblreenter() {
		return lblreenter;
	}

	public void setLblreenter(String lblreenter) {
		this.lblreenter = lblreenter;
	}

	public String getLblnavdata() {
		return lblnavdata;
	}

	public void setLblnavdata(String lblnavdata) {
		this.lblnavdata = lblnavdata;
	}

	public String getLblunauditedrate() {
		return lblunauditedrate;
	}

	public void setLblunauditedrate(String lblunauditedrate) {
		this.lblunauditedrate = lblunauditedrate;
	}

	public String getLblamendaudval() {
		return lblamendaudval;
	}

	public void setLblamendaudval(String lblamendaudval) {
		this.lblamendaudval = lblamendaudval;
	}

	public String getLblnotifieddate() {
		return lblnotifieddate;
	}

	public void setLblnotifieddate(String lblnotifieddate) {
		this.lblnotifieddate = lblnotifieddate;
	}

	public String getLblfund() {
		return lblfund;
	}

	public void setLblfund(String lblfund) {
		this.lblfund = lblfund;
	}

	public String getLblasofdate() {
		return lblasofdate;
	}

	public void setLblasofdate(String lblasofdate) {
		this.lblasofdate = lblasofdate;
	} 

   
        
}