package com.sic.tasa.dataobject;

import java.io.Serializable;  
/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2017 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class FrmNAVQueryBO implements Serializable{


    private String cmdexport; 

    private String cboinvstseq; 

    private String cbomipseq; 

    private String cmdclose; 

    private String chkadjfactor; 

    private String chkdividend; 

    private String cbofunds; 

    private String cmdselect; 

    private String lblexplanation; 

    private String lbltodate; 

    private String lblfromdate; 

    private String lblfund; 

    private String lblselect; 

    public String getCmdExport() {
        return cmdexport;
    }

    public void setCmdExport(String cmdexport ) {
        this.cmdexport = cmdexport;
    }
    
    public String getCboInvstSeq() {
        return cboinvstseq;
    }

    public void setCboInvstSeq(String cboinvstseq ) {
        this.cboinvstseq = cboinvstseq;
    }
    
    public String getCboMIPSeq() {
        return cbomipseq;
    }

    public void setCboMIPSeq(String cbomipseq ) {
        this.cbomipseq = cbomipseq;
    }
    
    public String getCmdClose() {
        return cmdclose;
    }

    public void setCmdClose(String cmdclose ) {
        this.cmdclose = cmdclose;
    }
    
    public String getChkAdjFactor() {
        return chkadjfactor;
    }

    public void setChkAdjFactor(String chkadjfactor ) {
        this.chkadjfactor = chkadjfactor;
    }
    
    public String getChkDividend() {
        return chkdividend;
    }

    public void setChkDividend(String chkdividend ) {
        this.chkdividend = chkdividend;
    }
    
    public String getCboFunds() {
        return cbofunds;
    }

    public void setCboFunds(String cbofunds ) {
        this.cbofunds = cbofunds;
    }
    
    public String getCmdSelect() {
        return cmdselect;
    }

    public void setCmdSelect(String cmdselect ) {
        this.cmdselect = cmdselect;
    }
    
    public String getLblExplanation() {
        return lblexplanation;
    }

    public void setLblExplanation(String lblexplanation ) {
        this.lblexplanation = lblexplanation;
    }
    
    public String getLblToDate() {
        return lbltodate;
    }

    public void setLblToDate(String lbltodate ) {
        this.lbltodate = lbltodate;
    }
    
    public String getLblFromDate() {
        return lblfromdate;
    }

    public void setLblFromDate(String lblfromdate ) {
        this.lblfromdate = lblfromdate;
    }
    
    public String getLblFund() {
        return lblfund;
    }

    public void setLblFund(String lblfund ) {
        this.lblfund = lblfund;
    }
    
    public String getLblSelect() {
        return lblselect;
    }

    public void setLblSelect(String lblselect ) {
        this.lblselect = lblselect;
    }
    
    @Override
    public String toString() {
      return "FrmNAVQueryBO [cmdexport = + cmdexport +  ,cboinvstseq = + cboinvstseq +  ,cbomipseq = + cbomipseq +  ,cmdclose = + cmdclose +  ,chkadjfactor = + chkadjfactor +  ,chkdividend = + chkdividend +  ,cbofunds = + cbofunds +  ,cmdselect = + cmdselect +  ,lblexplanation = + lblexplanation +  ,lbltodate = + lbltodate +  ,lblfromdate = + lblfromdate +  ,lblfund = + lblfund +  ,lblselect = + lblselect]";
    }
    
}