package com.sic.tasa.dataobject;

import java.io.Serializable;  
/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2017 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class FrmProductSeriesBO implements Serializable{


    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String cboApp;
	private String txtName;
	private String cmdClose;
	private String cmdRefresh;
	private String cmdQuery;
	private String txtIrma;
	private String shortName;
	private String irmaPrintFile;
	private String name;
	private String description;
	private String irmaFootNote;
	private String lastUpdated;
	public String getCboApp() {
		return cboApp;
	}
	public void setCboApp(String cboApp) {
		this.cboApp = cboApp;
	}
	public String getTxtName() {
		return txtName;
	}
	public void setTxtName(String txtName) {
		this.txtName = txtName;
	}
	public String getCmdClose() {
		return cmdClose;
	}
	public void setCmdClose(String cmdClose) {
		this.cmdClose = cmdClose;
	}
	public String getCmdRefresh() {
		return cmdRefresh;
	}
	public void setCmdRefresh(String cmdRefresh) {
		this.cmdRefresh = cmdRefresh;
	}
	public String getCmdQuery() {
		return cmdQuery;
	}
	public void setCmdQuery(String cmdQuery) {
		this.cmdQuery = cmdQuery;
	}
	public String getTxtIrma() {
		return txtIrma;
	}
	public void setTxtIrma(String txtIrma) {
		this.txtIrma = txtIrma;
	}
	public String getShortName() {
		return shortName;
	}
	public void setShortName(String shortName) {
		this.shortName = shortName;
	}
	public String getIrmaPrintFile() {
		return irmaPrintFile;
	}
	public void setIrmaPrintFile(String irmaPrintFile) {
		this.irmaPrintFile = irmaPrintFile;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getIrmaFootNote() {
		return irmaFootNote;
	}
	public void setIrmaFootNote(String irmaFootNote) {
		this.irmaFootNote = irmaFootNote;
	}
	public String getLastUpdated() {
		return lastUpdated;
	}
	public void setLastUpdated(String lastUpdated) {
		this.lastUpdated = lastUpdated;
	}
	@Override
	public String toString() {
		return "FrmProductSeriesBO [cboApp=" + cboApp + ", txtName=" + txtName + ", cmdClose=" + cmdClose
				+ ", cmdRefresh=" + cmdRefresh + ", cmdQuery=" + cmdQuery + ", txtIrma=" + txtIrma + ", shortName="
				+ shortName + ", irmaPrintFile=" + irmaPrintFile + ", name=" + name + ", description=" + description
				+ ", irmaFootNote=" + irmaFootNote + ", lastUpdated=" + lastUpdated + "]";
	}
	
	
	
}