package com.sic.tasa.dataobject;

import java.io.Serializable;

/*************************************************************************
 * 
 * SIC CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * SIC is a trademark of SIC Company.
 *
 * Copyright © 2017 SIC. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of SIC
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SIC and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SIC.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :

public class FrmProductFundsBO implements Serializable {

	private String updatedBy;
	private String asOfDateonFPU;
	private String invFundCategory;
	private String description;
	private String lastUpdated;

	public String getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public String getAsOfDateonFPU() {
		return asOfDateonFPU;
	}

	public void setAsOfDateonFPU(String asOfDateonFPU) {
		this.asOfDateonFPU = asOfDateonFPU;
	}

	public String getInvFundCategory() {
		return invFundCategory;
	}

	public void setInvFundCategory(String invFundCategory) {
		this.invFundCategory = invFundCategory;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLastUpdated() {
		return lastUpdated;
	}

	public void setLastUpdated(String lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Override
	public String toString() {
		return "FrmProductFundsBO [updatedBy =" + updatedBy + " ,asOfDateonFPU =" + asOfDateonFPU + " ,invFundCategory ="+ invFundCategory + " ,description ="+ description + " ,lastUpdated =" + lastUpdated+  "]";
	}

}