package com.sic.tasa.service.impl;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.sic.tasa.dataobject.FrmProductSeriesBO;
import com.sic.tasa.exceptions.TASABusinessException;
import com.sic.tasa.repositories.IFrmProductSeriesRepository;
import com.sic.tasa.service.IFrmProductSeriesService;
import com.sic.tasa.util.AtmaLogger;

/*************************************************************************
 * 
 * SIC CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * SIC is a trademark of SIC Company.
 *
 * Copyright ? 2017 SIC. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of SIC
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SIC and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SIC.
 *
 *************************************************************************/
// Author : Generated by ATMA ?
// Revision History :

@Service
public class FrmProductSeriesServiceImpl implements IFrmProductSeriesService {

	private static final AtmaLogger LOGGER = AtmaLogger.create(FrmProductSeriesServiceImpl.class);

	@Autowired
	private IFrmProductSeriesRepository frmproductseriesRepository;

	public void setFrmProductSeriesRepository(IFrmProductSeriesRepository frmproductseriesRepository) {
		this.frmproductseriesRepository = frmproductseriesRepository;
	}

	// in twips
	/**
	 * Method cboappclick
	 * 
	 * @param frmproductseriesBOReq
	 * @return frmproductseriesBOResp
	 * @throws TASABusinessException
	 */
	public List<FrmProductSeriesBO> cboappclick(FrmProductSeriesBO frmproductseriesBOReq) throws TASABusinessException {
		LOGGER.debug("Entering into the method: cboappclick()" + "argument : " + frmproductseriesBOReq);
		List<FrmProductSeriesBO> frmproductseriesBOResp = null;
		try {
			frmproductseriesBOResp = new ArrayList<FrmProductSeriesBO>();
			/*
			 * cmdQuery=true; cboApp.Width=1550; txtirma(.getSetfocus());
			 */
		} catch (Exception ex) {
			LOGGER.error("Error occurred in method: cboappclick()" + "and terminated due to " + ex.getMessage());
			throw new TASABusinessException(ex);
		}
		LOGGER.debug("Exiting the method: cboappclick()" + "return : " + frmproductseriesBOResp);
		return frmproductseriesBOResp;
	}
	/**
	 * Method cmdqueryclick
	 * 
	 * @param frmproductseriesBOReq
	 * @return frmproductseriesBOResp
	 * @throws TASABusinessException
	 */
	public List<FrmProductSeriesBO> cmdqueryclick(FrmProductSeriesBO frmproductseriesBOReq)
			throws TASABusinessException {
		LOGGER.debug("Entering into the method: cmdqueryclick()" + "argument : " + frmproductseriesBOReq);
		List<FrmProductSeriesBO> frmproductseriesBOResp = null;
		try {
			frmproductseriesBOResp = new ArrayList<FrmProductSeriesBO>();
			String strSQL;
			Boolean queryField;
			String sFund;
			queryField = false;
			frmproductseriesBOResp = frmproductseriesRepository.cmdqueryClick1(frmproductseriesBOReq);
			// build select string for query
			/*
			 * if(cboApp.Text != ""){ queryField=true; // takes the first four letters and
			 * strips off ending blanks sFund=VBUtilFunctions.left(cboApp.Text, 4);
			 * sFund=R(sFund).trim(); strSQL=strSQL + " SHORT_NAME = '" + sFund + "'"; }
			 * if(txtIRMA.Text != ""){ if(QueryField == true){ strSQL=strSQL +
			 * " && IRMA_PRINT_FL = '" + txtIRMA.Text + "'"; } } else{ strSQL=strSQL +
			 * " IRMA_PRINT_FL = '" + txtIRMA.Text + "'"; queryField=true; } }
			 * if(txtName.Text != ""){ if(QueryField == true){ strSQL=strSQL +
			 * " && NAME Like '" + txtName.Text + "%'"; } } else{ strSQL=strSQL +
			 * " NAME Like '" + txtName.Text + "%'"; queryField=true; }
			 * }strSQL=strSQL+" Order by IRMA_PRINT_FL Desc,SHORT_NAME ASC"; //
			 * Adodc.ConnectionString = cn adodc.RecordSource=strSQL;
			 * 
			 * adodc(.getRefresh()); if(Adodc.Recordset.EOF == true){
			 * fMainForm.sbStatusBar.SimpleText="No records found"; } }else
			 * 
			 * { fMainForm.sbStatusBar.SimpleText = ""; }
			 * 
			 * MsgBox(Err.Description);
			 */
		} catch (

		Exception ex) {
			LOGGER.error("Error occurred in method: cmdqueryclick()" + "and terminated due to " + ex.getMessage());
			throw new TASABusinessException(ex);
		}
		LOGGER.debug("Exiting the method: cmdqueryclick()" + "return : " + frmproductseriesBOResp);
		return frmproductseriesBOResp;
	}

/**
 * Method formload
 * @param frmproductseriesBOReq
 * @return frmproductseriesBOResp
 * @throws TASABusinessException
 */
public List<FrmProductSeriesBO> formload() throws TASABusinessException{
	LOGGER.debug("Entering into the method: formload()"+"argument : "); 
	List<FrmProductSeriesBO> frmproductseriesBOResp = null;
	try{
		frmproductseriesBOResp =  new ArrayList<FrmProductSeriesBO>();   
		/*ADODB.Recordset rs;
		String strSQL;
		//      fMainForm.mnuAdminProdFunds.Visible = True
		fMainForm.mnuMaintProdFund.Visible=true;
		cmdQuery=false;
		txtIRMA.Visible=true;
		cboApp.Visible=true;
		txtName.Visible=true;
		cmdQuery.Visible=true;
		cmdQuery=false;
		cmdRefresh.Visible=true;
		me.WindowState=vbMaximized;*/
		//  populate the App combo box
		frmproductseriesBOResp = frmproductseriesRepository.formLoad1();
		/*do{
			cboapp(.getAdditemRs(0)&&Rs(1));
			rs(.getMovenext());
			frmproductseriesBOResp = frmproductseriesRepository.formLoad2(frmproductseriesBOReq);
			adodc.ConnectionString=cn;
			adodc.RecordSource=strSQL;
			adodc(.getRefresh());
			dataGrid.Columns(2).Width=2600;
			dataGrid.Columns(3).Width=2700;
			dataGrid.Columns(4).Width=2000;
			dataGrid.Columns(5).Width=1650;
			dataGrid.HeadFont.Bold=true;
			mbDataChanged=false;
			fMainForm.sbStatusBar.SimpleText="Product Series short name";
			rs(.getClose());
			MsgBox(Err.Description);*/
		}catch (Exception ex){
			LOGGER.error("Error occurred in method: formload()"+"and terminated due to " + ex.getMessage());
			throw new TASABusinessException(ex);
		}
		LOGGER.debug("Exiting the method: formload()"+"return : "+frmproductseriesBOResp);
		return frmproductseriesBOResp;
	}

	/**
	 * Method txtirmakeypress
	 * 
	 * @param frmproductseriesBOReq
	 * @return frmproductseriesBOResp
	 * @throws TASABusinessException
	 */
	public List<FrmProductSeriesBO> txtirmakeypress(FrmProductSeriesBO frmproductseriesBOReq)
			throws TASABusinessException {
		LOGGER.debug("Entering into the method: txtirmakeypress()" + "argument : " + frmproductseriesBOReq);
		List<FrmProductSeriesBO> frmproductseriesBOResp = null;
		try {
			frmproductseriesBOResp = new ArrayList<FrmProductSeriesBO>();
			//cmdQuery = true;
		} catch (Exception ex) {
			LOGGER.error("Error occurred in method: txtirmakeypress()" + "and terminated due to " + ex.getMessage());
			throw new TASABusinessException(ex);
		}
		LOGGER.debug("Exiting the method: txtirmakeypress()" + "return : " + frmproductseriesBOResp);
		return frmproductseriesBOResp;
	}

	/**
	 * Method txtnamekeypress
	 * 
	 * @param frmproductseriesBOReq
	 * @return frmproductseriesBOResp
	 * @throws TASABusinessException
	 */
	public List<FrmProductSeriesBO> txtnamekeypress(FrmProductSeriesBO frmproductseriesBOReq)
			throws TASABusinessException {
		LOGGER.debug("Entering into the method: txtnamekeypress()" + "argument : " + frmproductseriesBOReq);
		List<FrmProductSeriesBO> frmproductseriesBOResp = null;
		try {
			frmproductseriesBOResp = new ArrayList<FrmProductSeriesBO>();
			//cmdQuery = true;
		} catch (Exception ex) {
			LOGGER.error("Error occurred in method: txtnamekeypress()" + "and terminated due to " + ex.getMessage());
			throw new TASABusinessException(ex);
		}
		LOGGER.debug("Exiting the method: txtnamekeypress()" + "return : " + frmproductseriesBOResp);
		return frmproductseriesBOResp;
	}

}