package com.sic.tasa.dataobject;

import java.io.Serializable;  
/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2017 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class FrmRelatedFundsBO implements Serializable{


    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String cboeInvstSeqSfg; 
    private String cboSfgnOnSfgFlag; 
    private String cmdSelFund; 
    private String cmdDown; 
    private String cmdUp; 
    private String cmdAdd; 
    private String cboAllFunds; 
    private String cboSfgFunds; 
    private String cmdClose; 
    private String cmdDelete; 
    private String cmdModify; 
    private String label4; 
    private String label2; 
    private String label1;
	public String getCboeInvstSeqSfg() {
		return cboeInvstSeqSfg;
	}
	public void setCboeInvstSeqSfg(String cboeInvstSeqSfg) {
		this.cboeInvstSeqSfg = cboeInvstSeqSfg;
	}
	public String getCboSfgnOnSfgFlag() {
		return cboSfgnOnSfgFlag;
	}
	public void setCboSfgnOnSfgFlag(String cboSfgnOnSfgFlag) {
		this.cboSfgnOnSfgFlag = cboSfgnOnSfgFlag;
	}
	public String getCmdSelFund() {
		return cmdSelFund;
	}
	public void setCmdSelFund(String cmdSelFund) {
		this.cmdSelFund = cmdSelFund;
	}
	public String getCmdDown() {
		return cmdDown;
	}
	public void setCmdDown(String cmdDown) {
		this.cmdDown = cmdDown;
	}
	public String getCmdUp() {
		return cmdUp;
	}
	public void setCmdUp(String cmdUp) {
		this.cmdUp = cmdUp;
	}
	public String getCmdAdd() {
		return cmdAdd;
	}
	public void setCmdAdd(String cmdAdd) {
		this.cmdAdd = cmdAdd;
	}
	public String getCboAllFunds() {
		return cboAllFunds;
	}
	public void setCboAllFunds(String cboAllFunds) {
		this.cboAllFunds = cboAllFunds;
	}
	public String getCboSfgFunds() {
		return cboSfgFunds;
	}
	public void setCboSfgFunds(String cboSfgFunds) {
		this.cboSfgFunds = cboSfgFunds;
	}
	public String getCmdClose() {
		return cmdClose;
	}
	public void setCmdClose(String cmdClose) {
		this.cmdClose = cmdClose;
	}
	public String getCmdDelete() {
		return cmdDelete;
	}
	public void setCmdDelete(String cmdDelete) {
		this.cmdDelete = cmdDelete;
	}
	public String getCmdModify() {
		return cmdModify;
	}
	public void setCmdModify(String cmdModify) {
		this.cmdModify = cmdModify;
	}
	public String getLabel4() {
		return label4;
	}
	public void setLabel4(String label4) {
		this.label4 = label4;
	}
	public String getLabel2() {
		return label2;
	}
	public void setLabel2(String label2) {
		this.label2 = label2;
	}
	public String getLabel1() {
		return label1;
	}
	public void setLabel1(String label1) {
		this.label1 = label1;
	}
	@Override
	public String toString() {
		return "FrmRelatedFundsBO [cboeInvstSeqSfg=" + cboeInvstSeqSfg + ", cboSfgnOnSfgFlag=" + cboSfgnOnSfgFlag
				+ ", cmdSelFund=" + cmdSelFund + ", cmdDown=" + cmdDown + ", cmdUp=" + cmdUp + ", cmdAdd=" + cmdAdd
				+ ", cboAllFunds=" + cboAllFunds + ", cboSfgFunds=" + cboSfgFunds + ", cmdClose=" + cmdClose
				+ ", cmdDelete=" + cmdDelete + ", cmdModify=" + cmdModify + ", label4=" + label4 + ", label2=" + label2
				+ ", label1=" + label1 + "]";
	}
    
	
}