package com.sic.tasa.repositories.impl;

import java.util.ArrayList;
import java.util.List;

import org.springframework.orm.hibernate4.HibernateTemplate;
import org.springframework.stereotype.Repository;

import com.sic.tasa.dataobject.FrmSEIMaintBO;
import com.sic.tasa.exceptions.TASADataAccessException;
import com.sic.tasa.repositories.IFrmSEIMaintRepository;
import com.sic.tasa.util.AtmaLogger;

/*************************************************************************
 * 
 * SIC CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * SIC is a trademark of SIC Company.
 *
 * Copyright ? 2017 SIC. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of SIC
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SIC and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SIC.
 *
 *************************************************************************/
// Author : Generated by ATMA ?
// Revision History :


@Repository
public class FrmSEIMaintRepositoryImpl implements IFrmSEIMaintRepository{

    private static AtmaLogger LOGGER = AtmaLogger.create(FrmSEIMaintRepositoryImpl.class);

    private HibernateTemplate template;
    
    
    /*
	 * Method formLoad1
	 * @param frmseimaintBOReq
	 * @return frmseimaintBOResp
	 * @throws TASADataAccessException
	 */    
    public List<FrmSEIMaintBO> formLoad1(FrmSEIMaintBO frmseimaintBOReq) throws TASADataAccessException {
        LOGGER.debug("Entering into the method: formLoad1 and argument : "+frmseimaintBOReq); 
        List<FrmSEIMaintBO> frmseimaintBOResp =new ArrayList<FrmSEIMaintBO>();
	   // String sql = "SELECT full_nm, rp_mip_seq, e_invst_instrument_seq "FROM rp_modified_investment_pool            "WHERE status_txt in ('SETUP', 'ACTIVE')             "and e_invst_instrument_seq is not null            "ORDER BY full_nm";
	    try {

	    	FrmSEIMaintBO bo = new FrmSEIMaintBO();
	    	bo.setCboFunds("CboFunds");
	    	bo.setCboMIPSeq("CboMIPSeq");
	    	frmseimaintBOResp.add(bo); 
	    	bo = new FrmSEIMaintBO();
	    	bo.setCboFunds("1");
	    	bo.setCboMIPSeq("5");
	    	frmseimaintBOResp.add(bo);
	    	bo = new FrmSEIMaintBO();
	    	bo.setCboFunds("2");
	    	bo.setCboMIPSeq("4");
	    	frmseimaintBOResp.add(bo);	    	 
	        // List<IDomainObj>  entityList = template.find(sql,new BeanPropertyRowMapper<IDomainObj>(<IDomainObj>.class));
	         //ObjectCopier.copy(entityList, frmadjfctrmaintBOResp);  
	    }catch (Exception ex) {
            LOGGER.error("Error occurred in method: formLoad1()" +"and terminated due to " + ex.getMessage());
            throw new TASADataAccessException(ex);
        }        
        LOGGER.debug("Exiting the method: formLoad1()"+"return : "+frmseimaintBOResp);
         return frmseimaintBOResp;
    }



    /*
	 * Method cbofundsClick1
	 * @param frmseimaintBOReq
	 * @return frmseimaintBOResp
	 * @throws TASADataAccessException
	 */
    public List<FrmSEIMaintBO> cbofundsClick1(FrmSEIMaintBO frmseimaintBOReq) throws TASADataAccessException {
	    LOGGER.debug("Entering into the method: cbofundsClick1 and argument : "+frmseimaintBOReq); 
	    List<FrmSEIMaintBO> frmseimaintBOResp =new ArrayList<FrmSEIMaintBO>();
	   // String sql = "select rp_mip_seq, daily_return_rt,daily_int_factor_nbr, as_of_dt, appld_rt_days_nbr from rp_fund_daily_return_rt where as_of_dt >= to_date(' format()(dteFrom, "mmddyyyy") + "', 'mmddyyyy') and as_of_dt <= to_date(format()(dteTo, "mmddyyyy") +  'mmddyyyy') and rp_mip_seq =  .cboMIPSeq.Text  order by as_of_dt desc";
	    try {	    	    	
	    	FrmSEIMaintBO bo = new FrmSEIMaintBO();
	    	bo.setCboFunds("CboFunds");
	    	bo.setCboMIPSeq("CboMIPSeq");
	    	frmseimaintBOResp.add(bo); 
	    	bo = new FrmSEIMaintBO();
	    	bo.setCboFunds("1");
	    	bo.setCboMIPSeq("5");
	    	frmseimaintBOResp.add(bo);
	    	bo = new FrmSEIMaintBO();
	    	bo.setCboFunds("2");
	    	bo.setCboMIPSeq("4");   
	    	
	    	frmseimaintBOResp.add(bo);
	    	
	    	
	    	
	    }catch (Exception ex) {
            LOGGER.error("Error occurred in method: cbofundsClick1()" +"and terminated due to " + ex.getMessage());
            throw new TASADataAccessException(ex);
        }        
        LOGGER.debug("Exiting the method: cbofundsClick1()"+"return : "+frmseimaintBOResp);
         return frmseimaintBOResp;
    }
    /*
	 * Method cmdrefreshClick1
	 * @param frmseimaintBOReq
	 * @return frmseimaintBOResp
	 * @throws TASADataAccessException
	 */
    public FrmSEIMaintBO cmdrefreshClick1(FrmSEIMaintBO frmseimaintBOReq) throws TASADataAccessException {
	    LOGGER.debug("Entering into the method: cmdrefreshClick1 and argument : "+frmseimaintBOReq); 
	    FrmSEIMaintBO frmseimaintBOResp =new FrmSEIMaintBO();
	  //  String sql = "SELECT a.weekend_ind FROM rp_modified_investment_pool a                   "WHERE a.rp_mip_seq =  (Me.cboMIPSeq.Text).trim();
	    try {
	  //       List<IDomainObj>  entityList = template.find(sql,new BeanPropertyRowMapper<IDomainObj>(<IDomainObj>.class));
	  //       ObjectCopier.copy(entityList, frmseimaintBOResp);  
	    	
//	    	frmseimaintBOResp.setWeekend_ind("W");
	    	frmseimaintBOResp.setWeekend_ind("N");
	    	           	    	
	    }catch (Exception ex) {
            LOGGER.error("Error occurred in method: cmdrefreshClick1()" +"and terminated due to " + ex.getMessage());
            throw new TASADataAccessException(ex);
        }        
        LOGGER.debug("Exiting the method: cmdrefreshClick1()"+"return : "+frmseimaintBOResp);
         return frmseimaintBOResp;
    }
    /*
	 * Method cmdsaveClick1
	 * @param frmseimaintBOReq
	 * @return frmseimaintBOResp
	 * @throws TASADataAccessException
	 */
    public boolean cmdsaveClick1(FrmSEIMaintBO frmseimaintBOReq) throws TASADataAccessException {
	    LOGGER.debug("Entering into the method: cmdsaveClick1 and argument : "+frmseimaintBOReq); 
	    //List<FrmSEIMaintBO> frmseimaintBOResp =new ArrayList<FrmSEIMaintBO>();
	   // String sql = "UPDATE rp_fund_daily_return_rt                         "set daily_return_rt = ";
	    boolean status;
	    try {
	   //      List<IDomainObj>  entityList = template.find(sql,new BeanPropertyRowMapper<IDomainObj>(<IDomainObj>.class));
	   //      ObjectCopier.copy(entityList, frmseimaintBOResp); 
	    	
	    	status = true;
	    	
	    }catch (Exception ex) {
	    	
	    	status = false;
            LOGGER.error("Error occurred in method: cmdsaveClick1()" +"and terminated due to " + ex.getMessage());
            throw new TASADataAccessException(ex);
            
        }
	    return status;
         
    }
    /*
	 * Method cmdsaveClick2
	 * @param frmseimaintBOReq
	 * @return frmseimaintBOResp
	 * @throws TASADataAccessException
	 */
    public boolean cmdsaveClick2(FrmSEIMaintBO frmseimaintBOReq) throws TASADataAccessException {
	    LOGGER.debug("Entering into the method: cmdsaveClick2 and argument : "+frmseimaintBOReq); 
	   // List<FrmSEIMaintBO> frmseimaintBOResp =new ArrayList<FrmSEIMaintBO>();
	   // String sql = "INSERT into rp_fund_daily_return_rt (                        "rp_mip_seq,                         "daily_return_rt,                         "as_of_dt,                         "appld_rt_days_nbr,                         "daily_int_factor_nbr)                         "VALUES(                         cboMIPSeq.Text + ",                         .SubItems(1) + ",                         "to_date('                        format()(.Text, "mm/dd/yyyy") + "','MM/DD/YYYY') ,                         .SubItems(3) + ",                         .SubItems(2) + ")";
	    boolean status;
	    try {
	      //   List<IDomainObj>  entityList = template.find(sql,new BeanPropertyRowMapper<IDomainObj>(<IDomainObj>.class));
	      //   ObjectCopier.copy(entityList, frmseimaintBOResp);  
	    	status = true;
	    	
	    }catch (Exception ex) {
	    	status=false;
            LOGGER.error("Error occurred in method: cmdsaveClick2()" +"and terminated due to " + ex.getMessage());
            throw new TASADataAccessException(ex);
        }
		return status;
    }
        
}