package com.sic.tasa.dataobject;

import java.io.Serializable;  
import java.util.Date;
/*************************************************************************
 * 
 * SIC CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * SIC is a trademark of SIC Company.
 *
 * Copyright © 2017 SIC. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of SIC
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SIC and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SIC.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class FrmUVEntryBO implements Serializable{


    private Double munitval; 

    private int i; 

    private int lenuvoverride; 

    private int irecaffected; 

    private int ianswer; 
    
    private String cmdAddModify;
    
    private String cboContract;
    
    private String txtUVOverride;
    
    private Date txtTodayDate;
    
    private String cboFund;
    
    
    
    public Double getMunitval() {
		return munitval;
	}



	public void setMunitval(Double munitval) {
		this.munitval = munitval;
	}



	public int getI() {
		return i;
	}



	public void setI(int i) {
		this.i = i;
	}



	public int getLenuvoverride() {
		return lenuvoverride;
	}



	public void setLenuvoverride(int lenuvoverride) {
		this.lenuvoverride = lenuvoverride;
	}



	public int getIrecaffected() {
		return irecaffected;
	}



	public void setIrecaffected(int irecaffected) {
		this.irecaffected = irecaffected;
	}



	public int getIanswer() {
		return ianswer;
	}



	public void setIanswer(int ianswer) {
		this.ianswer = ianswer;
	}



	public String getCmdAddModify() {
		return cmdAddModify;
	}



	public void setCmdAddModify(String cmdAddModify) {
		this.cmdAddModify = cmdAddModify;
	}



	public String getCboContract() {
		return cboContract;
	}



	public void setCboContract(String cboContract) {
		this.cboContract = cboContract;
	}



	public String getTxtUVOverride() {
		return txtUVOverride;
	}



	public void setTxtUVOverride(String txtUVOverride) {
		this.txtUVOverride = txtUVOverride;
	}



	public Date getTxtTodayDate() {
		return txtTodayDate;
	}



	public void setTxtTodayDate(Date txtTodayDate) {
		this.txtTodayDate = txtTodayDate;
	}



	public String getCboFund() {
		return cboFund;
	}



	public void setCboFund(String cboFund) {
		this.cboFund = cboFund;
	}

	@Override
    public String toString() {
      return "FrmUVEntryBO [munitval =" + munitval + " ,i =" + i + " ,lenuvoverride =" + lenuvoverride + " ,irecaffected =" + irecaffected + " ,ianswer =" + ianswer+ "]";
    }
    
}