package com.sic.tasa.service;

import java.util.List;

import com.sic.tasa.dataobject.FrmSEIMaintBO;
import com.sic.tasa.exceptions.TASABusinessException;

/*************************************************************************
 * 
 * sic CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * sic is a trademark of sic Company.
 *
 * Copyright ? 2017 sic. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of sic
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to sic and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from sic.
 *
 *************************************************************************/
// Author : Generated by ATMA ?
// Revision History : 


public interface IFrmSEIMaintService {

        public List<FrmSEIMaintBO> cbofundsclick(FrmSEIMaintBO frmseimaintBOReq) throws TASABusinessException;
        public List<FrmSEIMaintBO> cmdclearclick(FrmSEIMaintBO frmseimaintBOReq) throws TASABusinessException;
        public List<FrmSEIMaintBO> cmdcloseclick(FrmSEIMaintBO frmseimaintBOReq) throws TASABusinessException;
        public List<FrmSEIMaintBO> cmdrefreshclick(FrmSEIMaintBO frmseimaintBOReq) throws TASABusinessException;
        public List<FrmSEIMaintBO> cmdsaveclick(FrmSEIMaintBO frmseimaintBOReq) throws TASABusinessException;
        public List<FrmSEIMaintBO> dtpestexdatechange(FrmSEIMaintBO frmseimaintBOReq) throws TASABusinessException;
        public List<FrmSEIMaintBO> formload(FrmSEIMaintBO frmseimaintBOReq) throws TASABusinessException;
        public List<FrmSEIMaintBO> lvwdivdreturnrateitemclick(FrmSEIMaintBO frmseimaintBOReq) throws TASABusinessException;
        public List<FrmSEIMaintBO> txtestratechange(FrmSEIMaintBO frmseimaintBOReq) throws TASABusinessException;
        public List<FrmSEIMaintBO> txtestrategotfocus(FrmSEIMaintBO frmseimaintBOReq) throws TASABusinessException;
        public List<FrmSEIMaintBO> txtestratekeypress(FrmSEIMaintBO frmseimaintBOReq) throws TASABusinessException;
        public List<FrmSEIMaintBO> txtestratelostfocus(FrmSEIMaintBO frmseimaintBOReq) throws TASABusinessException;
}