package com.sic.tasa.repositories;

import java.util.List;

import com.sic.tasa.dataobject.FrmDivdMaintBO;
import com.sic.tasa.exceptions.TASADataAccessException;

/*************************************************************************
 * 
 * SIC CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * SIC is a trademark of SIC Company.
 *
 * Copyright © 2017 SIC. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of SIC
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SIC and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SIC.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :



public interface IFrmDivdMaintRepository{

    public List<FrmDivdMaintBO> cmdcomputenavClick1(FrmDivdMaintBO frmdivdmaintBOReq) throws TASADataAccessException;
    public List<FrmDivdMaintBO> cmdsaveClick1(FrmDivdMaintBO frmdivdmaintBOReq) throws TASADataAccessException;
    public List<FrmDivdMaintBO> cmdsaveClick2(FrmDivdMaintBO frmdivdmaintBOReq) throws TASADataAccessException;
    public List<FrmDivdMaintBO> cmdsaveClick3(FrmDivdMaintBO frmdivdmaintBOReq) throws TASADataAccessException;
    public List<FrmDivdMaintBO> cmdsaveClick4(FrmDivdMaintBO frmdivdmaintBOReq) throws TASADataAccessException;
    public List<FrmDivdMaintBO> cmdsaveClick5(FrmDivdMaintBO frmdivdmaintBOReq) throws TASADataAccessException;
    public List<FrmDivdMaintBO> cmdsaveClick6(FrmDivdMaintBO frmdivdmaintBOReq) throws TASADataAccessException;
    public List<FrmDivdMaintBO> cmdsaveClick7(FrmDivdMaintBO frmdivdmaintBOReq) throws TASADataAccessException;
    public List<FrmDivdMaintBO> cmdsaveClick8(FrmDivdMaintBO frmdivdmaintBOReq) throws TASADataAccessException;
    public List<FrmDivdMaintBO> cmdsaveClick9(FrmDivdMaintBO frmdivdmaintBOReq) throws TASADataAccessException;
    public List<FrmDivdMaintBO> cmdselectfundClick1(FrmDivdMaintBO frmdivdmaintBOReq) throws TASADataAccessException;
    public List<FrmDivdMaintBO> cmdselectfundClick2(FrmDivdMaintBO frmdivdmaintBOReq) throws TASADataAccessException;
    public List<FrmDivdMaintBO> formLoad1(FrmDivdMaintBO frmdivdmaintBOReq) throws TASADataAccessException;
    public List<FrmDivdMaintBO> formLoad2(FrmDivdMaintBO frmdivdmaintBOReq) throws TASADataAccessException;
}