package com.sic.tasa.repositories;

import java.util.List;

import com.sic.tasa.dataobject.FrmRelatedFundsBO;
import com.sic.tasa.exceptions.TASADataAccessException;

/*************************************************************************
 * 
 * SIC CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * SIC is a trademark of SIC Company.
 *
 * Copyright © 2017 SIC. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of SIC
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SIC and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SIC.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :



public interface IFrmRelatedFundsRepository{

    public List<FrmRelatedFundsBO> populatesfgfunds1(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASADataAccessException;
    public List<FrmRelatedFundsBO> populaterelatedfunds1(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASADataAccessException;
    public List<FrmRelatedFundsBO> populaterelatedfunds2(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASADataAccessException;
    public List<FrmRelatedFundsBO> cmdaddClick1(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASADataAccessException;
    public List<FrmRelatedFundsBO> cmdaddClick2(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASADataAccessException;
    public List<FrmRelatedFundsBO> cmdaddClick3(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASADataAccessException;
    public List<FrmRelatedFundsBO> getthehighestpriority1(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASADataAccessException;
    public List<FrmRelatedFundsBO> getthehighestpriority2(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASADataAccessException;
    public List<FrmRelatedFundsBO> cmddeleteClick1(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASADataAccessException;
    public List<FrmRelatedFundsBO> cmddeleteClick2(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASADataAccessException;
    public List<FrmRelatedFundsBO> updatepriority1(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASADataAccessException;
    public List<FrmRelatedFundsBO> updatepriority2(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASADataAccessException;
    public List<FrmRelatedFundsBO> selfundswithsameassetclass1(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASADataAccessException;
    public List<FrmRelatedFundsBO> selfundswithsameassetclass2(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASADataAccessException;
    public List<FrmRelatedFundsBO> selfundswithsameassetclass3(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASADataAccessException;
    public List<FrmRelatedFundsBO> showallfunds1(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASADataAccessException;
    public List<FrmRelatedFundsBO> showallfunds2(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASADataAccessException;
}