package com.sic.tasa.service;

import java.util.List;
import com.sic.tasa.dataobject.FrmNAVQueryBO;
import com.sic.tasa.exceptions.TASABusinessException;

/*************************************************************************
 * 
 * SIC CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * SIC is a trademark of SIC Company.
 *
 * Copyright ? 2017 SIC. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of SIC
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SIC and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SIC.
 *
 *************************************************************************/
// Author : Generated by ATMA ?
// Revision History : 


public interface IFrmNAVQueryService {

        public List<FrmNAVQueryBO> cbofundsclick(FrmNAVQueryBO frmnavqueryBOReq) throws TASABusinessException;
        public List<FrmNAVQueryBO> cmdcloseclick(FrmNAVQueryBO frmnavqueryBOReq) throws TASABusinessException;
        public List<FrmNAVQueryBO> cmdexportclick(FrmNAVQueryBO frmnavqueryBOReq) throws TASABusinessException;
        public List<FrmNAVQueryBO> cmdselectclick(FrmNAVQueryBO frmnavqueryBOReq) throws TASABusinessException;
        public List<FrmNAVQueryBO> formactivate(FrmNAVQueryBO frmnavqueryBOReq) throws TASABusinessException;
        public List<FrmNAVQueryBO> formload(FrmNAVQueryBO frmnavqueryBOReq) throws TASABusinessException;
        public List<FrmNAVQueryBO> formunload(FrmNAVQueryBO frmnavqueryBOReq) throws TASABusinessException;
        public List<FrmNAVQueryBO> populatelvwhistory(FrmNAVQueryBO frmnavqueryBOReq) throws TASABusinessException;
        public List<FrmNAVQueryBO> addadjfactorlvwhistory(FrmNAVQueryBO frmnavqueryBOReq) throws TASABusinessException;
        public List<FrmNAVQueryBO> adddividendlvwhistory(FrmNAVQueryBO frmnavqueryBOReq) throws TASABusinessException;
}