package com.sic.tasa.repositories;

import java.util.List;

import com.sic.tasa.dataobject.FrmGLAccountBO;
import com.sic.tasa.exceptions.TASADataAccessException;

/*************************************************************************
 * 
 * SIC CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * SIC is a trademark of SIC Company.
 *
 * Copyright © 2017 SIC. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of SIC
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SIC and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SIC.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :



public interface IFrmGLAccountRepository{

    public List<FrmGLAccountBO> cmdqueryClick1(FrmGLAccountBO frmglaccountBOReq) throws TASADataAccessException;
    public List<FrmGLAccountBO> formLoad1() throws TASADataAccessException;
    public List<FrmGLAccountBO> cmdinsertClick1(List<FrmGLAccountBO> frmglaccountBOReq) throws TASADataAccessException;
}