package com.sic.tasa.repositories;

import java.util.List;

import com.sic.tasa.dataobject.FrmDailyNavMaintenanceBO;
import com.sic.tasa.exceptions.TASADataAccessException;

/*************************************************************************
 * 
 * SIC CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * SIC is a trademark of SIC Company.
 *
 * Copyright © 2017 SIC. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of SIC
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SIC and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SIC.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :



public interface IFrmDailyNavMaintenanceRepository{

    public List<FrmDailyNavMaintenanceBO> populatesfgfund1() throws TASADataAccessException;
    public List<FrmDailyNavMaintenanceBO> cmdaddmodifyClick1(FrmDailyNavMaintenanceBO frmdailynavmaintenanceBOReq) throws TASADataAccessException;
    public List<FrmDailyNavMaintenanceBO> cmdaddmodifyClick2(FrmDailyNavMaintenanceBO frmdailynavmaintenanceBOReq) throws TASADataAccessException;
    public List<FrmDailyNavMaintenanceBO> cmdaddmodifyClick3(FrmDailyNavMaintenanceBO frmdailynavmaintenanceBOReq) throws TASADataAccessException;
    public List<FrmDailyNavMaintenanceBO> cmddeleteClick1(FrmDailyNavMaintenanceBO frmdailynavmaintenanceBOReq) throws TASADataAccessException;
    public List<FrmDailyNavMaintenanceBO> populateselectedfunddetails1(FrmDailyNavMaintenanceBO frmdailynavmaintenanceBOReq) throws TASADataAccessException;
    public List<FrmDailyNavMaintenanceBO> populateselectedfunddetails2(FrmDailyNavMaintenanceBO frmdailynavmaintenanceBOReq) throws TASADataAccessException;
}