package com.sic.tasa.service;

import java.util.List;
import com.sic.tasa.dataobject.FrmAdjFctrQueryBO;
import com.sic.tasa.exceptions.TASABusinessException;


/*************************************************************************
 * 
 * sic CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * sic is a trademark of sic Company.
 *
 * Copyright ? 2017 sic. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of sic
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to sic and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from sic.
 *
 *************************************************************************/
// Author : Generated by ATMA ?
// Revision History : 


public interface IFrmAdjFctrQueryService {

        public List<FrmAdjFctrQueryBO> cbofundsclick(FrmAdjFctrQueryBO frmadjfctrqueryBOReq) throws TASABusinessException;
        public List<FrmAdjFctrQueryBO> cmdcloseclick(FrmAdjFctrQueryBO frmadjfctrqueryBOReq) throws TASABusinessException;
        public List<FrmAdjFctrQueryBO> cmdshowcommentsclick(FrmAdjFctrQueryBO frmadjfctrqueryBOReq) throws TASABusinessException;
        public List<FrmAdjFctrQueryBO> formload(FrmAdjFctrQueryBO frmadjfctrqueryBOReq) throws TASABusinessException;
        public List<FrmAdjFctrQueryBO> lvwfundsitemclick(FrmAdjFctrQueryBO frmadjfctrqueryBOReq) throws TASABusinessException;
}