package com.sic.tasa.service;

import java.util.List;
import com.sic.tasa.dataobject.FrmNonSFGheldFundsBO;
import com.sic.tasa.exceptions.TASABusinessException;

/*************************************************************************
 * 
 * SIC CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * SIC is a trademark of SIC Company.
 *
 * Copyright ? 2017 SIC. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of SIC
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SIC and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SIC.
 *
 *************************************************************************/
// Author : Generated by ATMA ?
// Revision History : 


public interface IFrmNonSFGheldFundsService {

        public List<FrmNonSFGheldFundsBO> populateassetclasscombo(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> populatefunds(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> popassetclasscombowithunassigned(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> makeunassignedastext(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> selectassetclass(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> cboassetclasschange(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> cboassetclassclick(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> cbofundschange(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> cbofundsclick(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> cboselassetclassclick(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> cmdclearclick(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> cmdcloseclick(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> getsfgfundnames(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> cmddeleteclick(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> duplicatecusip(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> savechanges(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> cmdsaveclick(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> populatefunddetails(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> cmdselfundclick(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> enabledisablecontrols(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> formload(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> formunload(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> optfilterbyassetclassclick(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> optshowallclick(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> txtcusipchange(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> txtcusipkeypress(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> txtnamechange(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
        public List<FrmNonSFGheldFundsBO> txttickersymbolchange(FrmNonSFGheldFundsBO frmnonsfgheldfundsBOReq) throws TASABusinessException;
}