package com.sic.tasa.service;

import java.util.List;

import com.sic.tasa.dataobject.FrmRelatedFundsBO;
import com.sic.tasa.exceptions.TASABusinessException;

/*************************************************************************
 * 
 * SIC CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * SIC is a trademark of SIC Company.
 *
 * Copyright ? 2017 SIC. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of SIC
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SIC and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SIC.
 *
 *************************************************************************/
// Author : Generated by ATMA ?
// Revision History : 


public interface IFrmRelatedFundsService {

        public List<FrmRelatedFundsBO> populatesfgfunds(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
        public List<FrmRelatedFundsBO> populaterelatedfunds(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
        public List<FrmRelatedFundsBO> cboallfundsclick(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
        public List<FrmRelatedFundsBO> cbosfgfundsclick(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
        public List<FrmRelatedFundsBO> cmdaddclick(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
        public List<FrmRelatedFundsBO> getthehighestpriority(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
        public List<FrmRelatedFundsBO> cmdcloseclick(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
        public List<FrmRelatedFundsBO> reorderpriority(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
        public List<FrmRelatedFundsBO> cmddeleteclick(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
        public List<FrmRelatedFundsBO> cmddownclick(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
        public List<FrmRelatedFundsBO> updatepriority(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
        public List<FrmRelatedFundsBO> cmdmodifyclick(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
        public List<FrmRelatedFundsBO> cmdselfundclick(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
        public List<FrmRelatedFundsBO> cmdupclick(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
        public List<FrmRelatedFundsBO> formload(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
        public List<FrmRelatedFundsBO> formunload(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
        public List<FrmRelatedFundsBO> lvrelfundsclick(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
        public List<FrmRelatedFundsBO> lvrelfundscolumnclick(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
        public List<FrmRelatedFundsBO> selfundswithsameassetclass(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
        public List<FrmRelatedFundsBO> showallfunds(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
        public List<FrmRelatedFundsBO> optsameassetclassclick(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
        public List<FrmRelatedFundsBO> optshowallclick(FrmRelatedFundsBO frmrelatedfundsBOReq) throws TASABusinessException;
}