package com.sic.tasa.service;

import java.util.List;
import com.sic.tasa.dataobject.FrmDivdMaintBO;
import com.sic.tasa.exceptions.TASABusinessException;

/*************************************************************************
 * 
 * SIC CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * SIC is a trademark of SIC Company.
 *
 * Copyright ? 2017 SIC. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of SIC
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SIC and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SIC.
 *
 *************************************************************************/
// Author : Generated by ATMA ?
// Revision History : 


public interface IFrmDivdMaintService {

        public List<FrmDivdMaintBO> cboesttypecdclick(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> cbofundsclick(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> cmdclearclick(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> cmdcloseclick(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> cmdcomputenavclick(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> cmdrefreshclick(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> cmdsaveclick(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> cmdselectfundclick(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> dtpactreinvesteddatechange(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> dtpexdatechange(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> formload(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> formunload(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> lvwdividenditemclick(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> txtactdollarschange(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> txtactdollarsgotfocus(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> txtactdollarskeypress(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> txtactdollarslostfocus(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> txtactrategotfocus(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> txtactratekeypress(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> txtactratelostfocus(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> txtactshareschange(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> txtactsharesgotfocus(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> txtactshareskeypress(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> txtactshareslostfocus(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> txtestratechange(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> txtestrategotfocus(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> txtestratekeypress(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> txtestratelostfocus(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> txtnavauditedchange(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> txtnavauditedgotfocus(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> txtnavauditedkeypress(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
        public List<FrmDivdMaintBO> txtnavauditedlostfocus(FrmDivdMaintBO frmdivdmaintBOReq) throws TASABusinessException;
}