package com.sic.tasa.dataobject;

import java.io.Serializable;  
/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2017 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class ProcessStatusBO implements Serializable{


    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String txtName; 
    private String txtApp; 
    private String txtDate; 
    private String cmdQuery; 
    private String cmdRefresh; 
    private String cmdClose; 
    private String processNumber;
    private String processDate;
    private String application;
    private String name;
    private String returnCode;
    private String step;
    private String returnText;
	public String getTxtName() {
		return txtName;
	}
	public void setTxtName(String txtName) {
		this.txtName = txtName;
	}
	public String getTxtApp() {
		return txtApp;
	}
	public void setTxtApp(String txtApp) {
		this.txtApp = txtApp;
	}
	public String getTxtDate() {
		return txtDate;
	}
	public void setTxtDate(String txtDate) {
		this.txtDate = txtDate;
	}
	public String getCmdQuery() {
		return cmdQuery;
	}
	public void setCmdQuery(String cmdQuery) {
		this.cmdQuery = cmdQuery;
	}
	public String getCmdRefresh() {
		return cmdRefresh;
	}
	public void setCmdRefresh(String cmdRefresh) {
		this.cmdRefresh = cmdRefresh;
	}
	public String getCmdClose() {
		return cmdClose;
	}
	public void setCmdClose(String cmdClose) {
		this.cmdClose = cmdClose;
	}
	public String getProcessNumber() {
		return processNumber;
	}
	public void setProcessNumber(String processNumber) {
		this.processNumber = processNumber;
	}
	public String getProcessDate() {
		return processDate;
	}
	public void setProcessDate(String processDate) {
		this.processDate = processDate;
	}
	public String getApplication() {
		return application;
	}
	public void setApplication(String application) {
		this.application = application;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getReturnCode() {
		return returnCode;
	}
	public void setReturnCode(String returnCode) {
		this.returnCode = returnCode;
	}
	public String getStep() {
		return step;
	}
	public void setStep(String step) {
		this.step = step;
	}
	public String getReturnText() {
		return returnText;
	}
	public void setReturnText(String returnText) {
		this.returnText = returnText;
	}
	@Override
	public String toString() {
		return "ProcessStatusBO [txtName=" + txtName + ", txtApp=" + txtApp + ", txtDate=" + txtDate + ", cmdQuery="
				+ cmdQuery + ", cmdRefresh=" + cmdRefresh + ", cmdClose=" + cmdClose + ", processNumber="
				+ processNumber + ", processDate=" + processDate + ", application=" + application + ", name=" + name
				+ ", returnCode=" + returnCode + ", step=" + step + ", returnText=" + returnText + "]";
	}
    
	
       
}